<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzkKm50LlYUSYLmi96niB'."\n".'6r1JvkK2TLLKVAA/fioH2nE6ia33zLPZjBNZCXrlAbu69y0gwzxJolJMOhjKcQe8'."\n".'V+u0BlsZnRUuXiHnX33uQ4+8fThAoXd2g1IesSOiWDN8GgPIrisIM6LJfkl+dhLk'."\n".'KpKeHLm16vjh89zfwoLWoc/jWb6UUFBq4nEpC+HhQydzuxjFvu3yi9UmneckfKde'."\n".'er2MHf3OTpCuuj6LnBquwAqGb/ap9ueIW8r9YSq8hJ9b9rzVS7PPwMNadm6cyhTp'."\n".'UNRf02NFPFzpCvJYezF/bhvrfccvmLtdjH7n5a0XVCG74Y9s7dceZYIU8S/or53H'."\n".'FwIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
