<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2d8x82K\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2d8x82K/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container2d8x82K.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container2d8x82K\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container2d8x82K\appAppKernelProdContainer([
    'container.build_hash' => '2d8x82K',
    'container.build_id' => 'dd32fea4',
    'container.build_time' => 1717081563,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2d8x82K');
