<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZwWzui4\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZwWzui4/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZwWzui4.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZwWzui4\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerZwWzui4\appAppKernelDevDebugContainer([
    'container.build_hash' => 'ZwWzui4',
    'container.build_id' => '8ca300e8',
    'container.build_time' => 1717079968,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZwWzui4');
