<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVoG94P9\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVoG94P9/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVoG94P9.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVoG94P9\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerVoG94P9\appAppKernelDevDebugContainer([
    'container.build_hash' => 'VoG94P9',
    'container.build_id' => '373215b9',
    'container.build_time' => 1715952699,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVoG94P9');
